"""m6_durable_ingestion

Revision ID: 3308b9710dbc
Revises: d72e620b7302
"""
from alembic import op
import sqlalchemy as sa


revision = '3308b9710dbc'
down_revision = 'd72e620b7302'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_ingestion_runs',
    sa.Column('binding_id', sa.Uuid(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('parser_version', sa.String(length=50), nullable=False),
    sa.Column('chunker_version', sa.String(length=50), nullable=False),
    sa.Column('embedding_configuration', sa.String(length=200), nullable=False),
    sa.Column('normalized_artifact_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('request_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_type', sa.String(length=24), nullable=False),
    sa.Column('source_reference', sa.String(length=500), nullable=False),
    sa.Column('verification', sa.String(length=20), server_default='UNVERIFIED', nullable=False),
    sa.Column('correction_reason', sa.String(), nullable=True),
    sa.CheckConstraint("normalized_artifact_hash IS NULL OR normalized_artifact_hash ~ '^[0-9a-f]{64}$'", name=op.f('ck_rag_ingestion_runs_artifact_hash_format')),
    sa.CheckConstraint("source_type IN ('INSTITUTION','IMPORT','DOCUMENT','STUDENT','SYSTEM')", name=op.f('ck_rag_ingestion_runs_source_type_values')),
    sa.CheckConstraint("status IN ('RUNNING','FAILED','COMPLETED')", name=op.f('ck_rag_ingestion_runs_status_values')),
    sa.CheckConstraint("verification IN ('VERIFIED','SELF_DECLARED','UNVERIFIED')", name=op.f('ck_rag_ingestion_runs_verification_values')),
    sa.CheckConstraint('length(source_reference) > 0', name=op.f('ck_rag_ingestion_runs_source_present')),
    sa.CheckConstraint('length(trim(chunker_version)) > 0', name=op.f('ck_rag_ingestion_runs_chunker_version_required')),
    sa.CheckConstraint('length(trim(embedding_configuration)) > 0', name=op.f('ck_rag_ingestion_runs_embedding_configuration_required')),
    sa.CheckConstraint('length(trim(parser_version)) > 0', name=op.f('ck_rag_ingestion_runs_parser_version_required')),
    sa.CheckConstraint('schema_version > 0', name=op.f('ck_rag_ingestion_runs_positive_schema_version')),
    sa.ForeignKeyConstraint(['institution_id', 'actor_id'], ['users.institution_id', 'users.id'], name=op.f('fk_rag_ingestion_runs_institution_id_actor_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['institution_id', 'binding_id'], ['rag_policy_sources.institution_id', 'rag_policy_sources.id'], name=op.f('fk_rag_ingestion_runs_institution_id_binding_id_rag_policy_sources'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_rag_ingestion_runs_institution_id_institutions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rag_ingestion_runs')),
    sa.UniqueConstraint('institution_id', 'binding_id', 'schema_version', 'parser_version', 'chunker_version', 'embedding_configuration', name='uq_rag_ingestion_run_idempotency'),
    sa.UniqueConstraint('institution_id', 'id', name=op.f('uq_rag_ingestion_runs_institution_id_id'))
    )
    op.create_index(op.f('ix_rag_ingestion_runs_institution_id'), 'rag_ingestion_runs', ['institution_id'], unique=False)
    op.create_table('rag_chunks',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('section', sa.String(length=200), nullable=True),
    sa.Column('start_offset', sa.Integer(), nullable=True),
    sa.Column('end_offset', sa.Integer(), nullable=True),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('artifact_hash', sa.String(length=64), nullable=False),
    sa.Column('chunk_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('request_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_type', sa.String(length=24), nullable=False),
    sa.Column('source_reference', sa.String(length=500), nullable=False),
    sa.Column('verification', sa.String(length=20), server_default='UNVERIFIED', nullable=False),
    sa.Column('correction_reason', sa.String(), nullable=True),
    sa.CheckConstraint("artifact_hash ~ '^[0-9a-f]{64}$'", name=op.f('ck_rag_chunks_chunk_artifact_hash')),
    sa.CheckConstraint("chunk_hash ~ '^[0-9a-f]{64}$'", name=op.f('ck_rag_chunks_chunk_hash_format')),
    sa.CheckConstraint("source_hash ~ '^[0-9a-f]{64}$'", name=op.f('ck_rag_chunks_chunk_source_hash')),
    sa.CheckConstraint("source_type IN ('INSTITUTION','IMPORT','DOCUMENT','STUDENT','SYSTEM')", name=op.f('ck_rag_chunks_source_type_values')),
    sa.CheckConstraint("verification IN ('VERIFIED','SELF_DECLARED','UNVERIFIED')", name=op.f('ck_rag_chunks_verification_values')),
    sa.CheckConstraint('(start_offset IS NULL AND end_offset IS NULL) OR (start_offset IS NOT NULL AND end_offset IS NOT NULL AND start_offset >= 0 AND end_offset > start_offset)', name=op.f('ck_rag_chunks_chunk_offset_bounds')),
    sa.CheckConstraint('length(source_reference) > 0', name=op.f('ck_rag_chunks_source_present')),
    sa.CheckConstraint('ordinal >= 0', name=op.f('ck_rag_chunks_chunk_ordinal_bounds')),
    sa.CheckConstraint('page IS NOT NULL OR (section IS NOT NULL AND length(section) > 0) OR start_offset IS NOT NULL', name=op.f('ck_rag_chunks_chunk_locator_present')),
    sa.CheckConstraint('page IS NULL OR page > 0', name=op.f('ck_rag_chunks_chunk_page_bounds')),
    sa.ForeignKeyConstraint(['institution_id', 'actor_id'], ['users.institution_id', 'users.id'], name=op.f('fk_rag_chunks_institution_id_actor_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['institution_id', 'run_id'], ['rag_ingestion_runs.institution_id', 'rag_ingestion_runs.id'], name=op.f('fk_rag_chunks_institution_id_run_id_rag_ingestion_runs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_rag_chunks_institution_id_institutions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rag_chunks')),
    sa.UniqueConstraint('institution_id', 'id', name=op.f('uq_rag_chunks_institution_id_id')),
    sa.UniqueConstraint('institution_id', 'run_id', 'ordinal', name=op.f('uq_rag_chunks_institution_id_run_id_ordinal'))
    )
    op.create_index(op.f('ix_rag_chunks_institution_id'), 'rag_chunks', ['institution_id'], unique=False)
    op.create_table('rag_jobs',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('leased_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('request_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_type', sa.String(length=24), nullable=False),
    sa.Column('source_reference', sa.String(length=500), nullable=False),
    sa.Column('verification', sa.String(length=20), server_default='UNVERIFIED', nullable=False),
    sa.Column('correction_reason', sa.String(), nullable=True),
    sa.CheckConstraint("source_type IN ('INSTITUTION','IMPORT','DOCUMENT','STUDENT','SYSTEM')", name=op.f('ck_rag_jobs_source_type_values')),
    sa.CheckConstraint("status IN ('QUEUED','RUNNING','READY','REVIEW_REQUIRED','FAILED','CANCELLED')", name=op.f('ck_rag_jobs_status_values')),
    sa.CheckConstraint("verification IN ('VERIFIED','SELF_DECLARED','UNVERIFIED')", name=op.f('ck_rag_jobs_verification_values')),
    sa.CheckConstraint('attempt >= 0 AND attempt <= 3', name=op.f('ck_rag_jobs_job_attempt_bounds')),
    sa.CheckConstraint('length(source_reference) > 0', name=op.f('ck_rag_jobs_source_present')),
    sa.CheckConstraint('length(trim(stage)) > 0', name=op.f('ck_rag_jobs_stage_required')),
    sa.ForeignKeyConstraint(['institution_id', 'actor_id'], ['users.institution_id', 'users.id'], name=op.f('fk_rag_jobs_institution_id_actor_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['institution_id', 'run_id'], ['rag_ingestion_runs.institution_id', 'rag_ingestion_runs.id'], name=op.f('fk_rag_jobs_institution_id_run_id_rag_ingestion_runs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_rag_jobs_institution_id_institutions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rag_jobs')),
    sa.UniqueConstraint('institution_id', 'id', name=op.f('uq_rag_jobs_institution_id_id')),
    sa.UniqueConstraint('institution_id', 'run_id', name=op.f('uq_rag_jobs_institution_id_run_id'))
    )
    op.create_index(op.f('ix_rag_jobs_institution_id'), 'rag_jobs', ['institution_id'], unique=False)
    op.execute("""
        CREATE FUNCTION rag_guard_chunk_consistency() RETURNS trigger AS $$
        DECLARE
            run rag_ingestion_runs%ROWTYPE;
            binding rag_policy_sources%ROWTYPE;
        BEGIN
            SELECT * INTO run FROM rag_ingestion_runs
              WHERE institution_id = NEW.institution_id AND id = NEW.run_id;
            IF NOT FOUND THEN
                RAISE EXCEPTION 'RAG chunk run missing';
            END IF;
            
            SELECT * INTO binding FROM rag_policy_sources
              WHERE institution_id = run.institution_id AND id = run.binding_id;
            
            IF binding.source_hash <> NEW.source_hash THEN
                RAISE EXCEPTION 'RAG chunk source hash mismatch';
            END IF;
            
            IF run.normalized_artifact_hash IS NOT NULL AND run.normalized_artifact_hash <> NEW.artifact_hash THEN
                RAISE EXCEPTION 'RAG chunk artifact hash mismatch';
            END IF;
            
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;

        CREATE TRIGGER rag_chunk_consistency_guard
          BEFORE INSERT OR UPDATE ON rag_chunks
          FOR EACH ROW EXECUTE FUNCTION rag_guard_chunk_consistency();
    """)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER rag_chunk_consistency_guard ON rag_chunks")
    op.execute("DROP FUNCTION rag_guard_chunk_consistency()")
    op.drop_index(op.f('ix_rag_jobs_institution_id'), table_name='rag_jobs')
    op.drop_table('rag_jobs')
    op.drop_index(op.f('ix_rag_chunks_institution_id'), table_name='rag_chunks')
    op.drop_table('rag_chunks')
    op.drop_index(op.f('ix_rag_ingestion_runs_institution_id'), table_name='rag_ingestion_runs')
    op.drop_table('rag_ingestion_runs')
    # ### end Alembic commands ###
