"""Add conversation tables

Revision ID: 370d02e14256
Revises: eb348a12858e
"""
from alembic import op
import sqlalchemy as sa


revision = '370d02e14256'
down_revision = 'eb348a12858e'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_sessions',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_conversation_sessions_institution_id_institutions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_conversation_sessions_student_id_students'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_sessions'))
    )
    op.create_index(op.f('ix_conversation_sessions_institution_id'), 'conversation_sessions', ['institution_id'], unique=False)
    op.create_index(op.f('ix_conversation_sessions_student_id'), 'conversation_sessions', ['student_id'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('tool_name', sa.String(length=100), nullable=True),
    sa.Column('tool_call_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('message_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['conversation_sessions.id'], name=op.f('fk_conversation_messages_session_id_conversation_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_messages')),
    sa.UniqueConstraint('session_id', 'sequence_number', name='uq_session_sequence')
    )
    op.create_index(op.f('ix_conversation_messages_session_id'), 'conversation_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_messages_session_id'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index(op.f('ix_conversation_sessions_student_id'), table_name='conversation_sessions')
    op.drop_index(op.f('ix_conversation_sessions_institution_id'), table_name='conversation_sessions')
    op.drop_table('conversation_sessions')
    # ### end Alembic commands ###
