"""Add eligibility models

Revision ID: 7647b3ca528a
Revises: be3b6aafad0b
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "7647b3ca528a"
down_revision = "be3b6aafad0b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "eligibility_decisions",
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("opportunity_id", sa.Uuid(), nullable=False),
        sa.Column("policy_version_id", sa.Uuid(), nullable=False),
        sa.Column("requirement_version_id", sa.Uuid(), nullable=False),
        sa.Column("engine_version", sa.String(length=50), nullable=False),
        sa.Column("result", sa.String(length=20), nullable=False),
        sa.Column("evaluation_key", sa.String(length=64), nullable=False),
        sa.Column("snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reasons", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("institution_id", sa.Uuid(), nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column(
            "request_id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("source_type", sa.String(length=24), nullable=False),
        sa.Column("source_reference", sa.String(length=500), nullable=False),
        sa.Column(
            "verification", sa.String(length=20), server_default="UNVERIFIED", nullable=False
        ),
        sa.Column("correction_reason", sa.String(), nullable=True),
        sa.CheckConstraint(
            "jsonb_typeof(reasons) = 'array'", name=op.f("ck_eligibility_decisions_reasons_array")
        ),
        sa.CheckConstraint(
            "jsonb_typeof(snapshot) = 'object'",
            name=op.f("ck_eligibility_decisions_snapshot_object"),
        ),
        sa.CheckConstraint(
            "result IN ('ELIGIBLE','NOT_ELIGIBLE','UNKNOWN')",
            name=op.f("ck_eligibility_decisions_result_values"),
        ),
        sa.CheckConstraint(
            "source_type IN ('INSTITUTION','IMPORT','DOCUMENT','STUDENT','SYSTEM')",
            name=op.f("ck_eligibility_decisions_source_type_values"),
        ),
        sa.CheckConstraint(
            "verification IN ('VERIFIED','SELF_DECLARED','UNVERIFIED')",
            name=op.f("ck_eligibility_decisions_verification_values"),
        ),
        sa.CheckConstraint(
            "length(source_reference) > 0", name=op.f("ck_eligibility_decisions_source_present")
        ),
        sa.ForeignKeyConstraint(
            ["institution_id", "actor_id"],
            ["users.institution_id", "users.id"],
            name=op.f("fk_eligibility_decisions_institution_id_actor_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["institution_id", "opportunity_id"],
            ["placement_opportunities.institution_id", "placement_opportunities.id"],
            name=op.f(
                "fk_eligibility_decisions_institution_id_opportunity_id_placement_opportunities"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["institution_id", "policy_version_id"],
            ["policy_versions.institution_id", "policy_versions.id"],
            name=op.f("fk_eligibility_decisions_institution_id_policy_version_id_policy_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["institution_id", "requirement_version_id"],
            ["company_requirement_versions.institution_id", "company_requirement_versions.id"],
            name=op.f(
                "fk_eligibility_decisions_institution_id_requirement_version_id_company_requirement_versions"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["institution_id", "student_id"],
            ["students.institution_id", "students.id"],
            name=op.f("fk_eligibility_decisions_institution_id_student_id_students"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institutions.id"],
            name=op.f("fk_eligibility_decisions_institution_id_institutions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_eligibility_decisions")),
        sa.UniqueConstraint(
            "institution_id",
            "evaluation_key",
            name=op.f("uq_eligibility_decisions_institution_id_evaluation_key"),
        ),
        sa.UniqueConstraint(
            "institution_id", "id", name=op.f("uq_eligibility_decisions_institution_id_id")
        ),
    )
    op.create_index(
        op.f("ix_eligibility_decisions_institution_id"),
        "eligibility_decisions",
        ["institution_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_eligibility_decisions_institution_id"), table_name="eligibility_decisions"
    )
    op.drop_table("eligibility_decisions")
    # ### end Alembic commands ###
