"""m2_remediation_schema

Revision ID: be3b6aafad0b
Revises: 554daca0e585
"""
# M2 FINAL SYNCHRONIZATION
from alembic import op
import sqlalchemy as sa


revision = 'be3b6aafad0b'
down_revision = '554daca0e585'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_dream_approvals',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('academic_year_id', sa.Uuid(), nullable=False),
    sa.Column('declaration_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('request_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_type', sa.String(length=24), nullable=False),
    sa.Column('source_reference', sa.String(length=500), nullable=False),
    sa.Column('verification', sa.String(length=20), server_default='UNVERIFIED', nullable=False),
    sa.Column('correction_reason', sa.String(), nullable=True),
    sa.CheckConstraint("source_type IN ('INSTITUTION','IMPORT','DOCUMENT','STUDENT','SYSTEM')", name=op.f('ck_active_dream_approvals_source_type_values')),
    sa.CheckConstraint("verification IN ('VERIFIED','SELF_DECLARED','UNVERIFIED')", name=op.f('ck_active_dream_approvals_verification_values')),
    sa.CheckConstraint('length(source_reference) > 0', name=op.f('ck_active_dream_approvals_source_present')),
    sa.ForeignKeyConstraint(['institution_id', 'academic_year_id'], ['academic_years.institution_id', 'academic_years.id'], name=op.f('fk_active_dream_approvals_institution_id_academic_year_id_academic_years'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['institution_id', 'actor_id'], ['users.institution_id', 'users.id'], name=op.f('fk_active_dream_approvals_institution_id_actor_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['institution_id', 'student_id', 'academic_year_id', 'declaration_id'], ['student_dream_companies.institution_id', 'student_dream_companies.student_id', 'student_dream_companies.academic_year_id', 'student_dream_companies.id'], name=op.f('fk_active_dream_approvals_institution_id_student_id_academic_year_id_declaration_id_student_dream_companies')),
    sa.ForeignKeyConstraint(['institution_id', 'student_id'], ['students.institution_id', 'students.id'], name=op.f('fk_active_dream_approvals_institution_id_student_id_students'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_active_dream_approvals_institution_id_institutions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_active_dream_approvals')),
    sa.UniqueConstraint('institution_id', 'id', name=op.f('uq_active_dream_approvals_institution_id_id')),
    sa.UniqueConstraint('institution_id', 'student_id', 'academic_year_id', name=op.f('uq_active_dream_approvals_institution_id_student_id_academic_year_id'))
    )
    op.create_index(op.f('ix_active_dream_approvals_institution_id'), 'active_dream_approvals', ['institution_id'], unique=False)
    
    # 2. Append-Only Event Protection
    op.execute("""
    CREATE OR REPLACE FUNCTION enforce_append_only_history()
    RETURNS trigger AS $$
    BEGIN
        RAISE EXCEPTION 'Immutable event history: UPDATE and DELETE are not allowed';
    END;
    $$ LANGUAGE plpgsql;
    """)
    
    op.execute("CREATE TRIGGER tr_student_backlog_events_append_only BEFORE UPDATE OR DELETE ON student_backlog_events FOR EACH ROW EXECUTE FUNCTION enforce_append_only_history();")
    op.execute("CREATE TRIGGER tr_student_offer_events_append_only BEFORE UPDATE OR DELETE ON student_offer_events FOR EACH ROW EXECUTE FUNCTION enforce_append_only_history();")
    op.execute("CREATE TRIGGER tr_dream_declaration_events_append_only BEFORE UPDATE OR DELETE ON dream_declaration_events FOR EACH ROW EXECUTE FUNCTION enforce_append_only_history();")
    op.execute("CREATE TRIGGER tr_policy_lifecycle_events_append_only BEFORE UPDATE OR DELETE ON policy_lifecycle_events FOR EACH ROW EXECUTE FUNCTION enforce_append_only_history();")
    
    # 3. Definition Immutability
    op.execute("""
    CREATE OR REPLACE FUNCTION enforce_policy_version_immutability()
    RETURNS trigger AS $$
    BEGIN
        IF TG_OP = 'DELETE' AND OLD.status IN ('APPROVED', 'ACTIVE') THEN
            RAISE EXCEPTION 'Immutable definition: DELETE is not allowed on APPROVED/ACTIVE versions';
        END IF;
        
        IF TG_OP = 'UPDATE' AND OLD.status IN ('APPROVED', 'ACTIVE') THEN
            IF OLD.definition IS DISTINCT FROM NEW.definition 
               OR OLD.schema_version IS DISTINCT FROM NEW.schema_version 
               OR OLD.version IS DISTINCT FROM NEW.version THEN
                RAISE EXCEPTION 'Immutable definition: UPDATE is not allowed on payload for APPROVED/ACTIVE versions';
            END IF;
        END IF;
        
        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """)
    op.execute("CREATE TRIGGER tr_policy_versions_immutability BEFORE UPDATE OR DELETE ON policy_versions FOR EACH ROW EXECUTE FUNCTION enforce_policy_version_immutability();")
    
    op.execute("""
    CREATE OR REPLACE FUNCTION enforce_req_version_immutability()
    RETURNS trigger AS $$
    BEGIN
        IF TG_OP = 'DELETE' AND OLD.published_at IS NOT NULL THEN
            RAISE EXCEPTION 'Immutable definition: DELETE is not allowed on published requirement versions';
        END IF;
        
        IF TG_OP = 'UPDATE' AND OLD.published_at IS NOT NULL THEN
            IF OLD.compensation_id IS DISTINCT FROM NEW.compensation_id 
               OR OLD.version IS DISTINCT FROM NEW.version THEN
                RAISE EXCEPTION 'Immutable definition: UPDATE is not allowed on payload for published requirement versions';
            END IF;
        END IF;
        
        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """)
    op.execute("CREATE TRIGGER tr_company_req_versions_immutability BEFORE UPDATE OR DELETE ON company_requirement_versions FOR EACH ROW EXECUTE FUNCTION enforce_req_version_immutability();")

    op.execute("""
    CREATE OR REPLACE FUNCTION enforce_policy_rule_immutability()
    RETURNS trigger AS $$
    DECLARE
        v_status VARCHAR;
    BEGIN
        SELECT status INTO v_status FROM policy_versions WHERE id = COALESCE(OLD.policy_version_id, NEW.policy_version_id);
        IF v_status IN ('APPROVED', 'ACTIVE') THEN
            RAISE EXCEPTION 'Immutable definition: Modification of policy_rules is not allowed for APPROVED/ACTIVE policy versions';
        END IF;
        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """)
    op.execute("CREATE TRIGGER tr_policy_rules_immutability BEFORE INSERT OR UPDATE OR DELETE ON policy_rules FOR EACH ROW EXECUTE FUNCTION enforce_policy_rule_immutability();")

    op.execute("""
    CREATE OR REPLACE FUNCTION enforce_req_criterion_immutability()
    RETURNS trigger AS $$
    DECLARE
        v_published_at TIMESTAMP WITH TIME ZONE;
    BEGIN
        SELECT published_at INTO v_published_at FROM company_requirement_versions WHERE id = COALESCE(OLD.requirement_version_id, NEW.requirement_version_id);
        IF v_published_at IS NOT NULL THEN
            RAISE EXCEPTION 'Immutable definition: Modification of requirement_criteria is not allowed for published requirement versions';
        END IF;
        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """)
    op.execute("CREATE TRIGGER tr_requirement_criteria_immutability BEFORE INSERT OR UPDATE OR DELETE ON requirement_criteria FOR EACH ROW EXECUTE FUNCTION enforce_req_criterion_immutability();")

    op.execute("""
    CREATE OR REPLACE FUNCTION enforce_req_member_immutability()
    RETURNS trigger AS $$
    DECLARE
        v_published_at TIMESTAMP WITH TIME ZONE;
    BEGIN
        SELECT v.published_at INTO v_published_at 
        FROM company_requirement_versions v
        JOIN requirement_criteria c ON c.requirement_version_id = v.id
        WHERE c.id = COALESCE(OLD.criterion_id, NEW.criterion_id);
        
        IF v_published_at IS NOT NULL THEN
            RAISE EXCEPTION 'Immutable definition: Modification of requirement_set_members is not allowed for published requirement versions';
        END IF;
        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """)
    op.execute("CREATE TRIGGER tr_requirement_members_immutability BEFORE INSERT OR UPDATE OR DELETE ON requirement_set_members FOR EACH ROW EXECUTE FUNCTION enforce_req_member_immutability();")

    # ### end Alembic commands ###

def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS tr_requirement_members_immutability ON requirement_set_members;")
    op.execute("DROP FUNCTION IF EXISTS enforce_req_member_immutability();")
    
    op.execute("DROP TRIGGER IF EXISTS tr_requirement_criteria_immutability ON requirement_criteria;")
    op.execute("DROP FUNCTION IF EXISTS enforce_req_criterion_immutability();")
    
    op.execute("DROP TRIGGER IF EXISTS tr_policy_rules_immutability ON policy_rules;")
    op.execute("DROP FUNCTION IF EXISTS enforce_policy_rule_immutability();")

    op.execute("DROP TRIGGER IF EXISTS tr_company_req_versions_immutability ON company_requirement_versions;")
    op.execute("DROP FUNCTION IF EXISTS enforce_req_version_immutability();")

    op.execute("DROP TRIGGER IF EXISTS tr_policy_versions_immutability ON policy_versions;")
    op.execute("DROP FUNCTION IF EXISTS enforce_policy_version_immutability();")

    op.execute("DROP TRIGGER IF EXISTS tr_policy_lifecycle_events_append_only ON policy_lifecycle_events;")
    op.execute("DROP TRIGGER IF EXISTS tr_dream_declaration_events_append_only ON dream_declaration_events;")
    op.execute("DROP TRIGGER IF EXISTS tr_student_offer_events_append_only ON student_offer_events;")
    op.execute("DROP TRIGGER IF EXISTS tr_student_backlog_events_append_only ON student_backlog_events;")
    op.execute("DROP FUNCTION IF EXISTS enforce_append_only_history();")
    
    op.drop_index(op.f('ix_active_dream_approvals_institution_id'), table_name='active_dream_approvals')
    op.drop_table('active_dream_approvals')
    # ### end Alembic commands ###
