"""m6_rag_generation

Revision ID: eb348a12858e
Revises: 3308b9710dbc
"""
from alembic import op
import sqlalchemy as sa


revision = 'eb348a12858e'
down_revision = '3308b9710dbc'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_index_generations',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('space_id', sa.String(length=64), nullable=False),
    sa.Column('collection_name', sa.String(length=200), nullable=False),
    sa.Column('expected_chunk_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('request_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_type', sa.String(length=24), nullable=False),
    sa.Column('source_reference', sa.String(length=500), nullable=False),
    sa.Column('verification', sa.String(length=20), server_default='UNVERIFIED', nullable=False),
    sa.Column('correction_reason', sa.String(), nullable=True),
    sa.CheckConstraint("source_type IN ('INSTITUTION','IMPORT','DOCUMENT','STUDENT','SYSTEM')", name=op.f('ck_rag_index_generations_source_type_values')),
    sa.CheckConstraint("space_id ~ '^[0-9a-f]{64}$'", name=op.f('ck_rag_index_generations_generation_space_id_format')),
    sa.CheckConstraint("status IN ('PENDING','VERIFIED','PUBLISHED','FAILED')", name=op.f('ck_rag_index_generations_status_values')),
    sa.CheckConstraint("verification IN ('VERIFIED','SELF_DECLARED','UNVERIFIED')", name=op.f('ck_rag_index_generations_verification_values')),
    sa.CheckConstraint('expected_chunk_count >= 0', name=op.f('ck_rag_index_generations_generation_chunk_count_bounds')),
    sa.CheckConstraint('length(source_reference) > 0', name=op.f('ck_rag_index_generations_source_present')),
    sa.CheckConstraint('length(trim(collection_name)) > 0', name=op.f('ck_rag_index_generations_generation_collection_name_required')),
    sa.ForeignKeyConstraint(['institution_id', 'actor_id'], ['users.institution_id', 'users.id'], name=op.f('fk_rag_index_generations_institution_id_actor_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['institution_id', 'run_id'], ['rag_ingestion_runs.institution_id', 'rag_ingestion_runs.id'], name=op.f('fk_rag_index_generations_institution_id_run_id_rag_ingestion_runs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_rag_index_generations_institution_id_institutions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rag_index_generations')),
    sa.UniqueConstraint('institution_id', 'id', name=op.f('uq_rag_index_generations_institution_id_id')),
    sa.UniqueConstraint('institution_id', 'run_id', 'space_id', name=op.f('uq_rag_index_generations_institution_id_run_id_space_id'))
    )
    op.create_index(op.f('ix_rag_index_generations_institution_id'), 'rag_index_generations', ['institution_id'], unique=False)
    op.create_table('rag_published_generations',
    sa.Column('binding_id', sa.Uuid(), nullable=False),
    sa.Column('generation_id', sa.Uuid(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('institution_id', sa.Uuid(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('request_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_type', sa.String(length=24), nullable=False),
    sa.Column('source_reference', sa.String(length=500), nullable=False),
    sa.Column('verification', sa.String(length=20), server_default='UNVERIFIED', nullable=False),
    sa.Column('correction_reason', sa.String(), nullable=True),
    sa.CheckConstraint("source_type IN ('INSTITUTION','IMPORT','DOCUMENT','STUDENT','SYSTEM')", name=op.f('ck_rag_published_generations_source_type_values')),
    sa.CheckConstraint("verification IN ('VERIFIED','SELF_DECLARED','UNVERIFIED')", name=op.f('ck_rag_published_generations_verification_values')),
    sa.CheckConstraint('length(source_reference) > 0', name=op.f('ck_rag_published_generations_source_present')),
    sa.ForeignKeyConstraint(['institution_id', 'actor_id'], ['users.institution_id', 'users.id'], name=op.f('fk_rag_published_generations_institution_id_actor_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['institution_id', 'binding_id'], ['rag_policy_sources.institution_id', 'rag_policy_sources.id'], name=op.f('fk_rag_published_generations_institution_id_binding_id_rag_policy_sources'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['institution_id', 'generation_id'], ['rag_index_generations.institution_id', 'rag_index_generations.id'], name=op.f('fk_rag_published_generations_institution_id_generation_id_rag_index_generations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], name=op.f('fk_rag_published_generations_institution_id_institutions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rag_published_generations')),
    sa.UniqueConstraint('institution_id', 'binding_id', name=op.f('uq_rag_published_generations_institution_id_binding_id')),
    sa.UniqueConstraint('institution_id', 'generation_id', name=op.f('uq_rag_published_generations_institution_id_generation_id')),
    sa.UniqueConstraint('institution_id', 'id', name=op.f('uq_rag_published_generations_institution_id_id'))
    )
    op.create_index(op.f('ix_rag_published_generations_institution_id'), 'rag_published_generations', ['institution_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rag_published_generations_institution_id'), table_name='rag_published_generations')
    op.drop_table('rag_published_generations')
    op.drop_index(op.f('ix_rag_index_generations_institution_id'), table_name='rag_index_generations')
    op.drop_table('rag_index_generations')
    # ### end Alembic commands ###
